export const userConstants = {
  LOGIN_BEGIN: "USERS_LOGIN_BEGIN",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  SIGNUP_BEGIN: "USERS_SIGNUP_BEGIN",
  SIGNUP_SUCCESS: "USERS_SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "USERS_SIGNUP_FAILURE",

  LOGOUT: "USERS_LOGOUT",

  GETALL_BEGIN: "USERS_GETALL_BEGIN",
  GETALL_SUCCESS: "USERS_GETALL_SUCCESS",
  GETALL_FAILURE: "USERS_GETALL_FAILURE",
};
